// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BreadCharts.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class ApplicationUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DisplayName>k__BackingField")]
        public static extern ref string DisplayName(ApplicationUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ThirdPartyId>k__BackingField")]
        public static extern ref string ThirdPartyId(ApplicationUser @this);
    }
}
