// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        private ApplicationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("97c1a728-3449-429f-819f-73527f6e38bb"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var applicationUser = ApplicationUserEntityType.Create(this);
            var songVote = SongVoteEntityType.Create(this);
            var submittedSong = SubmittedSongEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);

            SongVoteEntityType.CreateForeignKey1(songVote, submittedSong);
            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, applicationUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, applicationUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, applicationUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, applicationUser);

            ApplicationUserEntityType.CreateAnnotations(applicationUser);
            SongVoteEntityType.CreateAnnotations(songVote);
            SubmittedSongEntityType.CreateAnnotations(submittedSong);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);

            AddAnnotation("ProductVersion", "10.0.5");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var applicationUser = FindEntityType("BreadCharts.Core.Models.ApplicationUser")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            applicationUser.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var breadChartsCoreModelsApplicationUserTableBase = new TableBase("BreadCharts.Core.Models.ApplicationUser", null, relationalModel);
            var accessFailedCountColumnBase = new ColumnBase<ColumnMappingBase>("AccessFailedCount", "INTEGER", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("AccessFailedCount", accessFailedCountColumnBase);
            var concurrencyStampColumnBase = new ColumnBase<ColumnMappingBase>("ConcurrencyStamp", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("ConcurrencyStamp", concurrencyStampColumnBase);
            var displayNameColumnBase = new ColumnBase<ColumnMappingBase>("DisplayName", "TEXT", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("DisplayName", displayNameColumnBase);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("Email", emailColumnBase);
            var emailConfirmedColumnBase = new ColumnBase<ColumnMappingBase>("EmailConfirmed", "INTEGER", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("EmailConfirmed", emailConfirmedColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("Id", idColumnBase);
            var lockoutEnabledColumnBase = new ColumnBase<ColumnMappingBase>("LockoutEnabled", "INTEGER", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("LockoutEnabled", lockoutEnabledColumnBase);
            var lockoutEndColumnBase = new ColumnBase<ColumnMappingBase>("LockoutEnd", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("LockoutEnd", lockoutEndColumnBase);
            var normalizedEmailColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedEmail", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("NormalizedEmail", normalizedEmailColumnBase);
            var normalizedUserNameColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedUserName", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("NormalizedUserName", normalizedUserNameColumnBase);
            var passwordHashColumnBase = new ColumnBase<ColumnMappingBase>("PasswordHash", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("PasswordHash", passwordHashColumnBase);
            var phoneNumberColumnBase = new ColumnBase<ColumnMappingBase>("PhoneNumber", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("PhoneNumber", phoneNumberColumnBase);
            var phoneNumberConfirmedColumnBase = new ColumnBase<ColumnMappingBase>("PhoneNumberConfirmed", "INTEGER", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("PhoneNumberConfirmed", phoneNumberConfirmedColumnBase);
            var securityStampColumnBase = new ColumnBase<ColumnMappingBase>("SecurityStamp", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("SecurityStamp", securityStampColumnBase);
            var thirdPartyIdColumnBase = new ColumnBase<ColumnMappingBase>("ThirdPartyId", "TEXT", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("ThirdPartyId", thirdPartyIdColumnBase);
            var twoFactorEnabledColumnBase = new ColumnBase<ColumnMappingBase>("TwoFactorEnabled", "INTEGER", breadChartsCoreModelsApplicationUserTableBase);
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("TwoFactorEnabled", twoFactorEnabledColumnBase);
            var userNameColumnBase = new ColumnBase<ColumnMappingBase>("UserName", "TEXT", breadChartsCoreModelsApplicationUserTableBase)
            {
                IsNullable = true
            };
            breadChartsCoreModelsApplicationUserTableBase.Columns.Add("UserName", userNameColumnBase);
            relationalModel.DefaultTables.Add("BreadCharts.Core.Models.ApplicationUser", breadChartsCoreModelsApplicationUserTableBase);
            var breadChartsCoreModelsApplicationUserMappingBase = new TableMappingBase<ColumnMappingBase>(applicationUser, breadChartsCoreModelsApplicationUserTableBase, null);
            breadChartsCoreModelsApplicationUserTableBase.AddTypeMapping(breadChartsCoreModelsApplicationUserMappingBase, false);
            defaultTableMappings.Add(breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, applicationUser.FindProperty("Id")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)accessFailedCountColumnBase, applicationUser.FindProperty("AccessFailedCount")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrencyStampColumnBase, applicationUser.FindProperty("ConcurrencyStamp")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)displayNameColumnBase, applicationUser.FindProperty("DisplayName")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, applicationUser.FindProperty("Email")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailConfirmedColumnBase, applicationUser.FindProperty("EmailConfirmed")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockoutEnabledColumnBase, applicationUser.FindProperty("LockoutEnabled")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lockoutEndColumnBase, applicationUser.FindProperty("LockoutEnd")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedEmailColumnBase, applicationUser.FindProperty("NormalizedEmail")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedUserNameColumnBase, applicationUser.FindProperty("NormalizedUserName")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordHashColumnBase, applicationUser.FindProperty("PasswordHash")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneNumberColumnBase, applicationUser.FindProperty("PhoneNumber")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneNumberConfirmedColumnBase, applicationUser.FindProperty("PhoneNumberConfirmed")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)securityStampColumnBase, applicationUser.FindProperty("SecurityStamp")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)thirdPartyIdColumnBase, applicationUser.FindProperty("ThirdPartyId")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)twoFactorEnabledColumnBase, applicationUser.FindProperty("TwoFactorEnabled")!, breadChartsCoreModelsApplicationUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userNameColumnBase, applicationUser.FindProperty("UserName")!, breadChartsCoreModelsApplicationUserMappingBase);

            var tableMappings = new List<TableMapping>();
            applicationUser.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var aspNetUsersTable = new Table("AspNetUsers", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(idColumn);
            var accessFailedCountColumn = new Column("AccessFailedCount", "INTEGER", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("AccessFailedCount", accessFailedCountColumn);
            accessFailedCountColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(accessFailedCountColumn);
            var concurrencyStampColumn = new Column("ConcurrencyStamp", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("ConcurrencyStamp", concurrencyStampColumn);
            concurrencyStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(concurrencyStampColumn);
            var displayNameColumn = new Column("DisplayName", "TEXT", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("DisplayName", displayNameColumn);
            displayNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(displayNameColumn);
            var emailColumn = new Column("Email", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("Email", emailColumn);
            emailColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(emailColumn);
            var emailConfirmedColumn = new Column("EmailConfirmed", "INTEGER", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("EmailConfirmed", emailConfirmedColumn);
            emailConfirmedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(emailConfirmedColumn);
            var lockoutEnabledColumn = new Column("LockoutEnabled", "INTEGER", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("LockoutEnabled", lockoutEnabledColumn);
            lockoutEnabledColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(lockoutEnabledColumn);
            var lockoutEndColumn = new Column("LockoutEnd", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("LockoutEnd", lockoutEndColumn);
            lockoutEndColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(lockoutEndColumn);
            var normalizedEmailColumn = new Column("NormalizedEmail", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("NormalizedEmail", normalizedEmailColumn);
            normalizedEmailColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedEmailColumn);
            var normalizedUserNameColumn = new Column("NormalizedUserName", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("NormalizedUserName", normalizedUserNameColumn);
            normalizedUserNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedUserNameColumn);
            var passwordHashColumn = new Column("PasswordHash", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("PasswordHash", passwordHashColumn);
            passwordHashColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(passwordHashColumn);
            var phoneNumberColumn = new Column("PhoneNumber", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("PhoneNumber", phoneNumberColumn);
            phoneNumberColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(phoneNumberColumn);
            var phoneNumberConfirmedColumn = new Column("PhoneNumberConfirmed", "INTEGER", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("PhoneNumberConfirmed", phoneNumberConfirmedColumn);
            phoneNumberConfirmedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(phoneNumberConfirmedColumn);
            var securityStampColumn = new Column("SecurityStamp", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("SecurityStamp", securityStampColumn);
            securityStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(securityStampColumn);
            var thirdPartyIdColumn = new Column("ThirdPartyId", "TEXT", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("ThirdPartyId", thirdPartyIdColumn);
            thirdPartyIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(thirdPartyIdColumn);
            var twoFactorEnabledColumn = new Column("TwoFactorEnabled", "INTEGER", aspNetUsersTable);
            aspNetUsersTable.Columns.Add("TwoFactorEnabled", twoFactorEnabledColumn);
            twoFactorEnabledColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(twoFactorEnabledColumn);
            var userNameColumn = new Column("UserName", "TEXT", aspNetUsersTable)
            {
                IsNullable = true
            };
            aspNetUsersTable.Columns.Add("UserName", userNameColumn);
            userNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userNameColumn);
            relationalModel.Tables.Add(("AspNetUsers", null), aspNetUsersTable);
            var aspNetUsersTableMapping = new TableMapping(applicationUser, aspNetUsersTable, null);
            aspNetUsersTable.AddTypeMapping(aspNetUsersTableMapping, false);
            tableMappings.Add(aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, applicationUser.FindProperty("Id")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(accessFailedCountColumn, applicationUser.FindProperty("AccessFailedCount")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(concurrencyStampColumn, applicationUser.FindProperty("ConcurrencyStamp")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(displayNameColumn, applicationUser.FindProperty("DisplayName")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, applicationUser.FindProperty("Email")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(emailConfirmedColumn, applicationUser.FindProperty("EmailConfirmed")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(lockoutEnabledColumn, applicationUser.FindProperty("LockoutEnabled")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(lockoutEndColumn, applicationUser.FindProperty("LockoutEnd")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(normalizedEmailColumn, applicationUser.FindProperty("NormalizedEmail")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(normalizedUserNameColumn, applicationUser.FindProperty("NormalizedUserName")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(passwordHashColumn, applicationUser.FindProperty("PasswordHash")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(phoneNumberColumn, applicationUser.FindProperty("PhoneNumber")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(phoneNumberConfirmedColumn, applicationUser.FindProperty("PhoneNumberConfirmed")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(securityStampColumn, applicationUser.FindProperty("SecurityStamp")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(thirdPartyIdColumn, applicationUser.FindProperty("ThirdPartyId")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(twoFactorEnabledColumn, applicationUser.FindProperty("TwoFactorEnabled")!, aspNetUsersTableMapping);
            RelationalModel.CreateColumnMapping(userNameColumn, applicationUser.FindProperty("UserName")!, aspNetUsersTableMapping);
            var pK_AspNetUsers = new UniqueConstraint("PK_AspNetUsers", aspNetUsersTable, new[] { idColumn });
            aspNetUsersTable.PrimaryKey = pK_AspNetUsers;
            pK_AspNetUsers.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_AspNetUsers));
            var pK_AspNetUsersKey = RelationalModel.GetKey(this,
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "Id" });
            pK_AspNetUsers.MappedKeys.Add(pK_AspNetUsersKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUsersKey).Add(pK_AspNetUsers);
            aspNetUsersTable.UniqueConstraints.Add("PK_AspNetUsers", pK_AspNetUsers);
            var emailIndex = new TableIndex(
            "EmailIndex", aspNetUsersTable, new[] { normalizedEmailColumn }, false);
            emailIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(emailIndex));
            var emailIndexIx = RelationalModel.GetIndex(this,
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "NormalizedEmail" });
            emailIndex.MappedIndexes.Add(emailIndexIx);
            RelationalModel.GetOrCreateTableIndexes(emailIndexIx).Add(emailIndex);
            aspNetUsersTable.Indexes.Add("EmailIndex", emailIndex);
            var userNameIndex = new TableIndex(
            "UserNameIndex", aspNetUsersTable, new[] { normalizedUserNameColumn }, true);
            userNameIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(userNameIndex));
            var userNameIndexIx = RelationalModel.GetIndex(this,
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "NormalizedUserName" });
            userNameIndex.MappedIndexes.Add(userNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(userNameIndexIx).Add(userNameIndex);
            aspNetUsersTable.Indexes.Add("UserNameIndex", userNameIndex);

            var songVote = FindEntityType("BreadCharts.Core.Models.SongVote")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            songVote.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var breadChartsCoreModelsSongVoteTableBase = new TableBase("BreadCharts.Core.Models.SongVote", null, relationalModel);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", breadChartsCoreModelsSongVoteTableBase);
            breadChartsCoreModelsSongVoteTableBase.Columns.Add("Id", idColumnBase0);
            var trackIdColumnBase = new ColumnBase<ColumnMappingBase>("TrackId", "TEXT", breadChartsCoreModelsSongVoteTableBase);
            breadChartsCoreModelsSongVoteTableBase.Columns.Add("TrackId", trackIdColumnBase);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", breadChartsCoreModelsSongVoteTableBase);
            breadChartsCoreModelsSongVoteTableBase.Columns.Add("UserId", userIdColumnBase);
            var votedAtUtcColumnBase = new ColumnBase<ColumnMappingBase>("VotedAtUtc", "TEXT", breadChartsCoreModelsSongVoteTableBase);
            breadChartsCoreModelsSongVoteTableBase.Columns.Add("VotedAtUtc", votedAtUtcColumnBase);
            relationalModel.DefaultTables.Add("BreadCharts.Core.Models.SongVote", breadChartsCoreModelsSongVoteTableBase);
            var breadChartsCoreModelsSongVoteMappingBase = new TableMappingBase<ColumnMappingBase>(songVote, breadChartsCoreModelsSongVoteTableBase, null);
            breadChartsCoreModelsSongVoteTableBase.AddTypeMapping(breadChartsCoreModelsSongVoteMappingBase, false);
            defaultTableMappings0.Add(breadChartsCoreModelsSongVoteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, songVote.FindProperty("Id")!, breadChartsCoreModelsSongVoteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)trackIdColumnBase, songVote.FindProperty("TrackId")!, breadChartsCoreModelsSongVoteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, songVote.FindProperty("UserId")!, breadChartsCoreModelsSongVoteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)votedAtUtcColumnBase, songVote.FindProperty("VotedAtUtc")!, breadChartsCoreModelsSongVoteMappingBase);

            var tableMappings0 = new List<TableMapping>();
            songVote.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var songVotesTable = new Table("SongVotes", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", songVotesTable);
            songVotesTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            var trackIdColumn = new Column("TrackId", "TEXT", songVotesTable);
            songVotesTable.Columns.Add("TrackId", trackIdColumn);
            trackIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(trackIdColumn);
            var userIdColumn = new Column("UserId", "TEXT", songVotesTable);
            songVotesTable.Columns.Add("UserId", userIdColumn);
            userIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn);
            var votedAtUtcColumn = new Column("VotedAtUtc", "TEXT", songVotesTable);
            songVotesTable.Columns.Add("VotedAtUtc", votedAtUtcColumn);
            votedAtUtcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(votedAtUtcColumn);
            relationalModel.Tables.Add(("SongVotes", null), songVotesTable);
            var songVotesTableMapping = new TableMapping(songVote, songVotesTable, null);
            songVotesTable.AddTypeMapping(songVotesTableMapping, false);
            tableMappings0.Add(songVotesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, songVote.FindProperty("Id")!, songVotesTableMapping);
            RelationalModel.CreateColumnMapping(trackIdColumn, songVote.FindProperty("TrackId")!, songVotesTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, songVote.FindProperty("UserId")!, songVotesTableMapping);
            RelationalModel.CreateColumnMapping(votedAtUtcColumn, songVote.FindProperty("VotedAtUtc")!, songVotesTableMapping);
            var pK_SongVotes = new UniqueConstraint("PK_SongVotes", songVotesTable, new[] { idColumn0 });
            songVotesTable.PrimaryKey = pK_SongVotes;
            pK_SongVotes.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_SongVotes));
            var pK_SongVotesKey = RelationalModel.GetKey(this,
                "BreadCharts.Core.Models.SongVote",
                new[] { "Id" });
            pK_SongVotes.MappedKeys.Add(pK_SongVotesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SongVotesKey).Add(pK_SongVotes);
            songVotesTable.UniqueConstraints.Add("PK_SongVotes", pK_SongVotes);
            var iX_SongVotes_TrackId_UserId = new TableIndex(
            "IX_SongVotes_TrackId_UserId", songVotesTable, new[] { trackIdColumn, userIdColumn }, true);
            iX_SongVotes_TrackId_UserId.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_SongVotes_TrackId_UserId));
            var iX_SongVotes_TrackId_UserIdIx = RelationalModel.GetIndex(this,
                "BreadCharts.Core.Models.SongVote",
                new[] { "TrackId", "UserId" });
            iX_SongVotes_TrackId_UserId.MappedIndexes.Add(iX_SongVotes_TrackId_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SongVotes_TrackId_UserIdIx).Add(iX_SongVotes_TrackId_UserId);
            songVotesTable.Indexes.Add("IX_SongVotes_TrackId_UserId", iX_SongVotes_TrackId_UserId);

            var submittedSong = FindEntityType("BreadCharts.Core.Models.SubmittedSong")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            submittedSong.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var breadChartsCoreModelsSubmittedSongTableBase = new TableBase("BreadCharts.Core.Models.SubmittedSong", null, relationalModel);
            var submittedAtUtcColumnBase = new ColumnBase<ColumnMappingBase>("SubmittedAtUtc", "TEXT", breadChartsCoreModelsSubmittedSongTableBase);
            breadChartsCoreModelsSubmittedSongTableBase.Columns.Add("SubmittedAtUtc", submittedAtUtcColumnBase);
            var submittedByUserIdColumnBase = new ColumnBase<ColumnMappingBase>("SubmittedByUserId", "TEXT", breadChartsCoreModelsSubmittedSongTableBase);
            breadChartsCoreModelsSubmittedSongTableBase.Columns.Add("SubmittedByUserId", submittedByUserIdColumnBase);
            var trackIdColumnBase0 = new ColumnBase<ColumnMappingBase>("TrackId", "TEXT", breadChartsCoreModelsSubmittedSongTableBase);
            breadChartsCoreModelsSubmittedSongTableBase.Columns.Add("TrackId", trackIdColumnBase0);
            var trackNameColumnBase = new ColumnBase<ColumnMappingBase>("TrackName", "TEXT", breadChartsCoreModelsSubmittedSongTableBase);
            breadChartsCoreModelsSubmittedSongTableBase.Columns.Add("TrackName", trackNameColumnBase);
            relationalModel.DefaultTables.Add("BreadCharts.Core.Models.SubmittedSong", breadChartsCoreModelsSubmittedSongTableBase);
            var breadChartsCoreModelsSubmittedSongMappingBase = new TableMappingBase<ColumnMappingBase>(submittedSong, breadChartsCoreModelsSubmittedSongTableBase, null);
            breadChartsCoreModelsSubmittedSongTableBase.AddTypeMapping(breadChartsCoreModelsSubmittedSongMappingBase, false);
            defaultTableMappings1.Add(breadChartsCoreModelsSubmittedSongMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)trackIdColumnBase0, submittedSong.FindProperty("TrackId")!, breadChartsCoreModelsSubmittedSongMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)submittedAtUtcColumnBase, submittedSong.FindProperty("SubmittedAtUtc")!, breadChartsCoreModelsSubmittedSongMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)submittedByUserIdColumnBase, submittedSong.FindProperty("SubmittedByUserId")!, breadChartsCoreModelsSubmittedSongMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)trackNameColumnBase, submittedSong.FindProperty("TrackName")!, breadChartsCoreModelsSubmittedSongMappingBase);

            var tableMappings1 = new List<TableMapping>();
            submittedSong.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var submittedSongsTable = new Table("SubmittedSongs", null, relationalModel);
            var trackIdColumn0 = new Column("TrackId", "TEXT", submittedSongsTable);
            submittedSongsTable.Columns.Add("TrackId", trackIdColumn0);
            trackIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(trackIdColumn0);
            var submittedAtUtcColumn = new Column("SubmittedAtUtc", "TEXT", submittedSongsTable);
            submittedSongsTable.Columns.Add("SubmittedAtUtc", submittedAtUtcColumn);
            submittedAtUtcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(submittedAtUtcColumn);
            var submittedByUserIdColumn = new Column("SubmittedByUserId", "TEXT", submittedSongsTable);
            submittedSongsTable.Columns.Add("SubmittedByUserId", submittedByUserIdColumn);
            submittedByUserIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(submittedByUserIdColumn);
            var trackNameColumn = new Column("TrackName", "TEXT", submittedSongsTable);
            submittedSongsTable.Columns.Add("TrackName", trackNameColumn);
            trackNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(trackNameColumn);
            relationalModel.Tables.Add(("SubmittedSongs", null), submittedSongsTable);
            var submittedSongsTableMapping = new TableMapping(submittedSong, submittedSongsTable, null);
            submittedSongsTable.AddTypeMapping(submittedSongsTableMapping, false);
            tableMappings1.Add(submittedSongsTableMapping);
            RelationalModel.CreateColumnMapping(trackIdColumn0, submittedSong.FindProperty("TrackId")!, submittedSongsTableMapping);
            RelationalModel.CreateColumnMapping(submittedAtUtcColumn, submittedSong.FindProperty("SubmittedAtUtc")!, submittedSongsTableMapping);
            RelationalModel.CreateColumnMapping(submittedByUserIdColumn, submittedSong.FindProperty("SubmittedByUserId")!, submittedSongsTableMapping);
            RelationalModel.CreateColumnMapping(trackNameColumn, submittedSong.FindProperty("TrackName")!, submittedSongsTableMapping);
            var pK_SubmittedSongs = new UniqueConstraint("PK_SubmittedSongs", submittedSongsTable, new[] { trackIdColumn0 });
            submittedSongsTable.PrimaryKey = pK_SubmittedSongs;
            pK_SubmittedSongs.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_SubmittedSongs));
            var pK_SubmittedSongsKey = RelationalModel.GetKey(this,
                "BreadCharts.Core.Models.SubmittedSong",
                new[] { "TrackId" });
            pK_SubmittedSongs.MappedKeys.Add(pK_SubmittedSongsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SubmittedSongsKey).Add(pK_SubmittedSongs);
            submittedSongsTable.UniqueConstraints.Add("PK_SubmittedSongs", pK_SubmittedSongs);

            var identityRole = FindEntityType("Microsoft.AspNetCore.Identity.IdentityRole")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            identityRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var microsoftAspNetCoreIdentityIdentityRoleTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityRole", null, relationalModel);
            var concurrencyStampColumnBase0 = new ColumnBase<ColumnMappingBase>("ConcurrencyStamp", "TEXT", microsoftAspNetCoreIdentityIdentityRoleTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleTableBase.Columns.Add("ConcurrencyStamp", concurrencyStampColumnBase0);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", microsoftAspNetCoreIdentityIdentityRoleTableBase);
            microsoftAspNetCoreIdentityIdentityRoleTableBase.Columns.Add("Id", idColumnBase1);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", microsoftAspNetCoreIdentityIdentityRoleTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleTableBase.Columns.Add("Name", nameColumnBase);
            var normalizedNameColumnBase = new ColumnBase<ColumnMappingBase>("NormalizedName", "TEXT", microsoftAspNetCoreIdentityIdentityRoleTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleTableBase.Columns.Add("NormalizedName", normalizedNameColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityRole", microsoftAspNetCoreIdentityIdentityRoleTableBase);
            var microsoftAspNetCoreIdentityIdentityRoleMappingBase = new TableMappingBase<ColumnMappingBase>(identityRole, microsoftAspNetCoreIdentityIdentityRoleTableBase, null);
            microsoftAspNetCoreIdentityIdentityRoleTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityRoleMappingBase, false);
            defaultTableMappings2.Add(microsoftAspNetCoreIdentityIdentityRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, identityRole.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)concurrencyStampColumnBase0, identityRole.FindProperty("ConcurrencyStamp")!, microsoftAspNetCoreIdentityIdentityRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, identityRole.FindProperty("Name")!, microsoftAspNetCoreIdentityIdentityRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)normalizedNameColumnBase, identityRole.FindProperty("NormalizedName")!, microsoftAspNetCoreIdentityIdentityRoleMappingBase);

            var tableMappings2 = new List<TableMapping>();
            identityRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var aspNetRolesTable = new Table("AspNetRoles", null, relationalModel);
            var idColumn1 = new Column("Id", "TEXT", aspNetRolesTable);
            aspNetRolesTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(idColumn1);
            var concurrencyStampColumn0 = new Column("ConcurrencyStamp", "TEXT", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("ConcurrencyStamp", concurrencyStampColumn0);
            concurrencyStampColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(concurrencyStampColumn0);
            var nameColumn = new Column("Name", "TEXT", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var normalizedNameColumn = new Column("NormalizedName", "TEXT", aspNetRolesTable)
            {
                IsNullable = true
            };
            aspNetRolesTable.Columns.Add("NormalizedName", normalizedNameColumn);
            normalizedNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(normalizedNameColumn);
            relationalModel.Tables.Add(("AspNetRoles", null), aspNetRolesTable);
            var aspNetRolesTableMapping = new TableMapping(identityRole, aspNetRolesTable, null);
            aspNetRolesTable.AddTypeMapping(aspNetRolesTableMapping, false);
            tableMappings2.Add(aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, identityRole.FindProperty("Id")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(concurrencyStampColumn0, identityRole.FindProperty("ConcurrencyStamp")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, identityRole.FindProperty("Name")!, aspNetRolesTableMapping);
            RelationalModel.CreateColumnMapping(normalizedNameColumn, identityRole.FindProperty("NormalizedName")!, aspNetRolesTableMapping);
            var pK_AspNetRoles = new UniqueConstraint("PK_AspNetRoles", aspNetRolesTable, new[] { idColumn1 });
            aspNetRolesTable.PrimaryKey = pK_AspNetRoles;
            pK_AspNetRoles.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_AspNetRoles));
            var pK_AspNetRolesKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRole",
                new[] { "Id" });
            pK_AspNetRoles.MappedKeys.Add(pK_AspNetRolesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetRolesKey).Add(pK_AspNetRoles);
            aspNetRolesTable.UniqueConstraints.Add("PK_AspNetRoles", pK_AspNetRoles);
            var roleNameIndex = new TableIndex(
            "RoleNameIndex", aspNetRolesTable, new[] { normalizedNameColumn }, true);
            roleNameIndex.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(roleNameIndex));
            var roleNameIndexIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityRole",
                new[] { "NormalizedName" });
            roleNameIndex.MappedIndexes.Add(roleNameIndexIx);
            RelationalModel.GetOrCreateTableIndexes(roleNameIndexIx).Add(roleNameIndex);
            aspNetRolesTable.Indexes.Add("RoleNameIndex", roleNameIndex);

            var identityRoleClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", null, relationalModel);
            var claimTypeColumnBase = new ColumnBase<ColumnMappingBase>("ClaimType", "TEXT", microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase.Columns.Add("ClaimType", claimTypeColumnBase);
            var claimValueColumnBase = new ColumnBase<ColumnMappingBase>("ClaimValue", "TEXT", microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase.Columns.Add("ClaimValue", claimValueColumnBase);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase.Columns.Add("Id", idColumnBase2);
            var roleIdColumnBase = new ColumnBase<ColumnMappingBase>("RoleId", "TEXT", microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase);
            microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase.Columns.Add("RoleId", roleIdColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase);
            var microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase = new TableMappingBase<ColumnMappingBase>(identityRoleClaim, microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase, null);
            microsoftAspNetCoreIdentityIdentityRoleClaimstringTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase, false);
            defaultTableMappings3.Add(microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, identityRoleClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimTypeColumnBase, identityRoleClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimValueColumnBase, identityRoleClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase, identityRoleClaim.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityRoleClaimstringMappingBase);

            var tableMappings3 = new List<TableMapping>();
            identityRoleClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var aspNetRoleClaimsTable = new Table("AspNetRoleClaims", null, relationalModel);
            var idColumn2 = new Column("Id", "INTEGER", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("Id", idColumn2);
            idColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn2);
            var claimTypeColumn = new Column("ClaimType", "TEXT", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("ClaimType", claimTypeColumn);
            claimTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimTypeColumn);
            var claimValueColumn = new Column("ClaimValue", "TEXT", aspNetRoleClaimsTable)
            {
                IsNullable = true
            };
            aspNetRoleClaimsTable.Columns.Add("ClaimValue", claimValueColumn);
            claimValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimValueColumn);
            var roleIdColumn = new Column("RoleId", "TEXT", aspNetRoleClaimsTable);
            aspNetRoleClaimsTable.Columns.Add("RoleId", roleIdColumn);
            roleIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(roleIdColumn);
            relationalModel.Tables.Add(("AspNetRoleClaims", null), aspNetRoleClaimsTable);
            var aspNetRoleClaimsTableMapping = new TableMapping(identityRoleClaim, aspNetRoleClaimsTable, null);
            aspNetRoleClaimsTable.AddTypeMapping(aspNetRoleClaimsTableMapping, false);
            tableMappings3.Add(aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, identityRoleClaim.FindProperty("Id")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimTypeColumn, identityRoleClaim.FindProperty("ClaimType")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimValueColumn, identityRoleClaim.FindProperty("ClaimValue")!, aspNetRoleClaimsTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn, identityRoleClaim.FindProperty("RoleId")!, aspNetRoleClaimsTableMapping);
            var pK_AspNetRoleClaims = new UniqueConstraint("PK_AspNetRoleClaims", aspNetRoleClaimsTable, new[] { idColumn2 });
            aspNetRoleClaimsTable.PrimaryKey = pK_AspNetRoleClaims;
            pK_AspNetRoleClaims.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_AspNetRoleClaims));
            var pK_AspNetRoleClaimsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>",
                new[] { "Id" });
            pK_AspNetRoleClaims.MappedKeys.Add(pK_AspNetRoleClaimsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetRoleClaimsKey).Add(pK_AspNetRoleClaims);
            aspNetRoleClaimsTable.UniqueConstraints.Add("PK_AspNetRoleClaims", pK_AspNetRoleClaims);
            var iX_AspNetRoleClaims_RoleId = new TableIndex(
            "IX_AspNetRoleClaims_RoleId", aspNetRoleClaimsTable, new[] { roleIdColumn }, false);
            iX_AspNetRoleClaims_RoleId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_AspNetRoleClaims_RoleId));
            var iX_AspNetRoleClaims_RoleIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>",
                new[] { "RoleId" });
            iX_AspNetRoleClaims_RoleId.MappedIndexes.Add(iX_AspNetRoleClaims_RoleIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetRoleClaims_RoleIdIx).Add(iX_AspNetRoleClaims_RoleId);
            aspNetRoleClaimsTable.Indexes.Add("IX_AspNetRoleClaims_RoleId", iX_AspNetRoleClaims_RoleId);

            var identityUserClaim = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserClaim.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", null, relationalModel);
            var claimTypeColumnBase0 = new ColumnBase<ColumnMappingBase>("ClaimType", "TEXT", microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase.Columns.Add("ClaimType", claimTypeColumnBase0);
            var claimValueColumnBase0 = new ColumnBase<ColumnMappingBase>("ClaimValue", "TEXT", microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase.Columns.Add("ClaimValue", claimValueColumnBase0);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase.Columns.Add("Id", idColumnBase3);
            var userIdColumnBase0 = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase.Columns.Add("UserId", userIdColumnBase0);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase);
            var microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserClaim, microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserClaimstringTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase, false);
            defaultTableMappings4.Add(microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, identityUserClaim.FindProperty("Id")!, microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimTypeColumnBase0, identityUserClaim.FindProperty("ClaimType")!, microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)claimValueColumnBase0, identityUserClaim.FindProperty("ClaimValue")!, microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase0, identityUserClaim.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserClaimstringMappingBase);

            var tableMappings4 = new List<TableMapping>();
            identityUserClaim.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var aspNetUserClaimsTable = new Table("AspNetUserClaims", null, relationalModel);
            var idColumn3 = new Column("Id", "INTEGER", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("Id", idColumn3);
            idColumn3.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn3);
            var claimTypeColumn0 = new Column("ClaimType", "TEXT", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("ClaimType", claimTypeColumn0);
            claimTypeColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimTypeColumn0);
            var claimValueColumn0 = new Column("ClaimValue", "TEXT", aspNetUserClaimsTable)
            {
                IsNullable = true
            };
            aspNetUserClaimsTable.Columns.Add("ClaimValue", claimValueColumn0);
            claimValueColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(claimValueColumn0);
            var userIdColumn0 = new Column("UserId", "TEXT", aspNetUserClaimsTable);
            aspNetUserClaimsTable.Columns.Add("UserId", userIdColumn0);
            userIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn0);
            relationalModel.Tables.Add(("AspNetUserClaims", null), aspNetUserClaimsTable);
            var aspNetUserClaimsTableMapping = new TableMapping(identityUserClaim, aspNetUserClaimsTable, null);
            aspNetUserClaimsTable.AddTypeMapping(aspNetUserClaimsTableMapping, false);
            tableMappings4.Add(aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn3, identityUserClaim.FindProperty("Id")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimTypeColumn0, identityUserClaim.FindProperty("ClaimType")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(claimValueColumn0, identityUserClaim.FindProperty("ClaimValue")!, aspNetUserClaimsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn0, identityUserClaim.FindProperty("UserId")!, aspNetUserClaimsTableMapping);
            var pK_AspNetUserClaims = new UniqueConstraint("PK_AspNetUserClaims", aspNetUserClaimsTable, new[] { idColumn3 });
            aspNetUserClaimsTable.PrimaryKey = pK_AspNetUserClaims;
            pK_AspNetUserClaims.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_AspNetUserClaims));
            var pK_AspNetUserClaimsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<string>",
                new[] { "Id" });
            pK_AspNetUserClaims.MappedKeys.Add(pK_AspNetUserClaimsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserClaimsKey).Add(pK_AspNetUserClaims);
            aspNetUserClaimsTable.UniqueConstraints.Add("PK_AspNetUserClaims", pK_AspNetUserClaims);
            var iX_AspNetUserClaims_UserId = new TableIndex(
            "IX_AspNetUserClaims_UserId", aspNetUserClaimsTable, new[] { userIdColumn0 }, false);
            iX_AspNetUserClaims_UserId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_AspNetUserClaims_UserId));
            var iX_AspNetUserClaims_UserIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<string>",
                new[] { "UserId" });
            iX_AspNetUserClaims_UserId.MappedIndexes.Add(iX_AspNetUserClaims_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserClaims_UserIdIx).Add(iX_AspNetUserClaims_UserId);
            aspNetUserClaimsTable.Indexes.Add("IX_AspNetUserClaims_UserId", iX_AspNetUserClaims_UserId);

            var identityUserLogin = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserLogin.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", null, relationalModel);
            var loginProviderColumnBase = new ColumnBase<ColumnMappingBase>("LoginProvider", "TEXT", microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase.Columns.Add("LoginProvider", loginProviderColumnBase);
            var providerDisplayNameColumnBase = new ColumnBase<ColumnMappingBase>("ProviderDisplayName", "TEXT", microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase.Columns.Add("ProviderDisplayName", providerDisplayNameColumnBase);
            var providerKeyColumnBase = new ColumnBase<ColumnMappingBase>("ProviderKey", "TEXT", microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase.Columns.Add("ProviderKey", providerKeyColumnBase);
            var userIdColumnBase1 = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase.Columns.Add("UserId", userIdColumnBase1);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase);
            var microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserLogin, microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserLoginstringTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase, false);
            defaultTableMappings5.Add(microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginProviderColumnBase, identityUserLogin.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)providerKeyColumnBase, identityUserLogin.FindProperty("ProviderKey")!, microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)providerDisplayNameColumnBase, identityUserLogin.FindProperty("ProviderDisplayName")!, microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase1, identityUserLogin.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserLoginstringMappingBase);

            var tableMappings5 = new List<TableMapping>();
            identityUserLogin.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var aspNetUserLoginsTable = new Table("AspNetUserLogins", null, relationalModel);
            var loginProviderColumn = new Column("LoginProvider", "TEXT", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("LoginProvider", loginProviderColumn);
            loginProviderColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginProviderColumn);
            var providerKeyColumn = new Column("ProviderKey", "TEXT", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("ProviderKey", providerKeyColumn);
            providerKeyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(providerKeyColumn);
            var providerDisplayNameColumn = new Column("ProviderDisplayName", "TEXT", aspNetUserLoginsTable)
            {
                IsNullable = true
            };
            aspNetUserLoginsTable.Columns.Add("ProviderDisplayName", providerDisplayNameColumn);
            providerDisplayNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(providerDisplayNameColumn);
            var userIdColumn1 = new Column("UserId", "TEXT", aspNetUserLoginsTable);
            aspNetUserLoginsTable.Columns.Add("UserId", userIdColumn1);
            userIdColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn1);
            relationalModel.Tables.Add(("AspNetUserLogins", null), aspNetUserLoginsTable);
            var aspNetUserLoginsTableMapping = new TableMapping(identityUserLogin, aspNetUserLoginsTable, null);
            aspNetUserLoginsTable.AddTypeMapping(aspNetUserLoginsTableMapping, false);
            tableMappings5.Add(aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(loginProviderColumn, identityUserLogin.FindProperty("LoginProvider")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(providerKeyColumn, identityUserLogin.FindProperty("ProviderKey")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(providerDisplayNameColumn, identityUserLogin.FindProperty("ProviderDisplayName")!, aspNetUserLoginsTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn1, identityUserLogin.FindProperty("UserId")!, aspNetUserLoginsTableMapping);
            var pK_AspNetUserLogins = new UniqueConstraint("PK_AspNetUserLogins", aspNetUserLoginsTable, new[] { loginProviderColumn, providerKeyColumn });
            aspNetUserLoginsTable.PrimaryKey = pK_AspNetUserLogins;
            pK_AspNetUserLogins.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserLogins));
            var pK_AspNetUserLoginsKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<string>",
                new[] { "LoginProvider", "ProviderKey" });
            pK_AspNetUserLogins.MappedKeys.Add(pK_AspNetUserLoginsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserLoginsKey).Add(pK_AspNetUserLogins);
            aspNetUserLoginsTable.UniqueConstraints.Add("PK_AspNetUserLogins", pK_AspNetUserLogins);
            var iX_AspNetUserLogins_UserId = new TableIndex(
            "IX_AspNetUserLogins_UserId", aspNetUserLoginsTable, new[] { userIdColumn1 }, false);
            iX_AspNetUserLogins_UserId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_AspNetUserLogins_UserId));
            var iX_AspNetUserLogins_UserIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<string>",
                new[] { "UserId" });
            iX_AspNetUserLogins_UserId.MappedIndexes.Add(iX_AspNetUserLogins_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserLogins_UserIdIx).Add(iX_AspNetUserLogins_UserId);
            aspNetUserLoginsTable.Indexes.Add("IX_AspNetUserLogins_UserId", iX_AspNetUserLogins_UserId);

            var identityUserRole = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserRole.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var microsoftAspNetCoreIdentityIdentityUserRolestringTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", null, relationalModel);
            var roleIdColumnBase0 = new ColumnBase<ColumnMappingBase>("RoleId", "TEXT", microsoftAspNetCoreIdentityIdentityUserRolestringTableBase);
            microsoftAspNetCoreIdentityIdentityUserRolestringTableBase.Columns.Add("RoleId", roleIdColumnBase0);
            var userIdColumnBase2 = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", microsoftAspNetCoreIdentityIdentityUserRolestringTableBase);
            microsoftAspNetCoreIdentityIdentityUserRolestringTableBase.Columns.Add("UserId", userIdColumnBase2);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", microsoftAspNetCoreIdentityIdentityUserRolestringTableBase);
            var microsoftAspNetCoreIdentityIdentityUserRolestringMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserRole, microsoftAspNetCoreIdentityIdentityUserRolestringTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserRolestringTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserRolestringMappingBase, false);
            defaultTableMappings6.Add(microsoftAspNetCoreIdentityIdentityUserRolestringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase0, identityUserRole.FindProperty("RoleId")!, microsoftAspNetCoreIdentityIdentityUserRolestringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase2, identityUserRole.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserRolestringMappingBase);

            var tableMappings6 = new List<TableMapping>();
            identityUserRole.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var aspNetUserRolesTable = new Table("AspNetUserRoles", null, relationalModel);
            var userIdColumn2 = new Column("UserId", "TEXT", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("UserId", userIdColumn2);
            userIdColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn2);
            var roleIdColumn0 = new Column("RoleId", "TEXT", aspNetUserRolesTable);
            aspNetUserRolesTable.Columns.Add("RoleId", roleIdColumn0);
            roleIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(roleIdColumn0);
            relationalModel.Tables.Add(("AspNetUserRoles", null), aspNetUserRolesTable);
            var aspNetUserRolesTableMapping = new TableMapping(identityUserRole, aspNetUserRolesTable, null);
            aspNetUserRolesTable.AddTypeMapping(aspNetUserRolesTableMapping, false);
            tableMappings6.Add(aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn0, identityUserRole.FindProperty("RoleId")!, aspNetUserRolesTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn2, identityUserRole.FindProperty("UserId")!, aspNetUserRolesTableMapping);
            var pK_AspNetUserRoles = new UniqueConstraint("PK_AspNetUserRoles", aspNetUserRolesTable, new[] { userIdColumn2, roleIdColumn0 });
            aspNetUserRolesTable.PrimaryKey = pK_AspNetUserRoles;
            pK_AspNetUserRoles.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserRoles));
            var pK_AspNetUserRolesKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<string>",
                new[] { "UserId", "RoleId" });
            pK_AspNetUserRoles.MappedKeys.Add(pK_AspNetUserRolesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserRolesKey).Add(pK_AspNetUserRoles);
            aspNetUserRolesTable.UniqueConstraints.Add("PK_AspNetUserRoles", pK_AspNetUserRoles);
            var iX_AspNetUserRoles_RoleId = new TableIndex(
            "IX_AspNetUserRoles_RoleId", aspNetUserRolesTable, new[] { roleIdColumn0 }, false);
            iX_AspNetUserRoles_RoleId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_AspNetUserRoles_RoleId));
            var iX_AspNetUserRoles_RoleIdIx = RelationalModel.GetIndex(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<string>",
                new[] { "RoleId" });
            iX_AspNetUserRoles_RoleId.MappedIndexes.Add(iX_AspNetUserRoles_RoleIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AspNetUserRoles_RoleIdIx).Add(iX_AspNetUserRoles_RoleId);
            aspNetUserRolesTable.Indexes.Add("IX_AspNetUserRoles_RoleId", iX_AspNetUserRoles_RoleId);

            var identityUserToken = FindEntityType("Microsoft.AspNetCore.Identity.IdentityUserToken<string>")!;

            var defaultTableMappings7 = new List<TableMappingBase<ColumnMappingBase>>();
            identityUserToken.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings7);
            var microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase = new TableBase("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", null, relationalModel);
            var loginProviderColumnBase0 = new ColumnBase<ColumnMappingBase>("LoginProvider", "TEXT", microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase.Columns.Add("LoginProvider", loginProviderColumnBase0);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase.Columns.Add("Name", nameColumnBase0);
            var userIdColumnBase3 = new ColumnBase<ColumnMappingBase>("UserId", "TEXT", microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase);
            microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase.Columns.Add("UserId", userIdColumnBase3);
            var valueColumnBase = new ColumnBase<ColumnMappingBase>("Value", "TEXT", microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase)
            {
                IsNullable = true
            };
            microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase.Columns.Add("Value", valueColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase);
            var microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase = new TableMappingBase<ColumnMappingBase>(identityUserToken, microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase, null);
            microsoftAspNetCoreIdentityIdentityUserTokenstringTableBase.AddTypeMapping(microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase, false);
            defaultTableMappings7.Add(microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)loginProviderColumnBase0, identityUserToken.FindProperty("LoginProvider")!, microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, identityUserToken.FindProperty("Name")!, microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase3, identityUserToken.FindProperty("UserId")!, microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueColumnBase, identityUserToken.FindProperty("Value")!, microsoftAspNetCoreIdentityIdentityUserTokenstringMappingBase);

            var tableMappings7 = new List<TableMapping>();
            identityUserToken.SetRuntimeAnnotation("Relational:TableMappings", tableMappings7);
            var aspNetUserTokensTable = new Table("AspNetUserTokens", null, relationalModel);
            var userIdColumn3 = new Column("UserId", "TEXT", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("UserId", userIdColumn3);
            userIdColumn3.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userIdColumn3);
            var loginProviderColumn0 = new Column("LoginProvider", "TEXT", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("LoginProvider", loginProviderColumn0);
            loginProviderColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(loginProviderColumn0);
            var nameColumn0 = new Column("Name", "TEXT", aspNetUserTokensTable);
            aspNetUserTokensTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            var valueColumn = new Column("Value", "TEXT", aspNetUserTokensTable)
            {
                IsNullable = true
            };
            aspNetUserTokensTable.Columns.Add("Value", valueColumn);
            valueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(valueColumn);
            relationalModel.Tables.Add(("AspNetUserTokens", null), aspNetUserTokensTable);
            var aspNetUserTokensTableMapping = new TableMapping(identityUserToken, aspNetUserTokensTable, null);
            aspNetUserTokensTable.AddTypeMapping(aspNetUserTokensTableMapping, false);
            tableMappings7.Add(aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(loginProviderColumn0, identityUserToken.FindProperty("LoginProvider")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, identityUserToken.FindProperty("Name")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn3, identityUserToken.FindProperty("UserId")!, aspNetUserTokensTableMapping);
            RelationalModel.CreateColumnMapping(valueColumn, identityUserToken.FindProperty("Value")!, aspNetUserTokensTableMapping);
            var pK_AspNetUserTokens = new UniqueConstraint("PK_AspNetUserTokens", aspNetUserTokensTable, new[] { userIdColumn3, loginProviderColumn0, nameColumn0 });
            aspNetUserTokensTable.PrimaryKey = pK_AspNetUserTokens;
            pK_AspNetUserTokens.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_AspNetUserTokens));
            var pK_AspNetUserTokensKey = RelationalModel.GetKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<string>",
                new[] { "UserId", "LoginProvider", "Name" });
            pK_AspNetUserTokens.MappedKeys.Add(pK_AspNetUserTokensKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AspNetUserTokensKey).Add(pK_AspNetUserTokens);
            aspNetUserTokensTable.UniqueConstraints.Add("PK_AspNetUserTokens", pK_AspNetUserTokens);
            var fK_AspNetRoleClaims_AspNetRoles_RoleId = new ForeignKeyConstraint(
                "FK_AspNetRoleClaims_AspNetRoles_RoleId", aspNetRoleClaimsTable, aspNetRolesTable,
                new[] { roleIdColumn },
                aspNetRolesTable.FindUniqueConstraint("PK_AspNetRoles")!, ReferentialAction.Cascade);
            fK_AspNetRoleClaims_AspNetRoles_RoleId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetRoleClaims_AspNetRoles_RoleId));
            var fK_AspNetRoleClaims_AspNetRoles_RoleIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>",
                new[] { "RoleId" },
                "Microsoft.AspNetCore.Identity.IdentityRole",
                new[] { "Id" });
            fK_AspNetRoleClaims_AspNetRoles_RoleId.MappedForeignKeys.Add(fK_AspNetRoleClaims_AspNetRoles_RoleIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetRoleClaims_AspNetRoles_RoleIdFk).Add(fK_AspNetRoleClaims_AspNetRoles_RoleId);
            aspNetRoleClaimsTable.ForeignKeyConstraints.Add(fK_AspNetRoleClaims_AspNetRoles_RoleId);
            aspNetRolesTable.ReferencingForeignKeyConstraints.Add(fK_AspNetRoleClaims_AspNetRoles_RoleId);
            var fK_AspNetUserClaims_AspNetUsers_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserClaims_AspNetUsers_UserId", aspNetUserClaimsTable, aspNetUsersTable,
                new[] { userIdColumn0 },
                aspNetUsersTable.FindUniqueConstraint("PK_AspNetUsers")!, ReferentialAction.Cascade);
            fK_AspNetUserClaims_AspNetUsers_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetUserClaims_AspNetUsers_UserId));
            var fK_AspNetUserClaims_AspNetUsers_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<string>",
                new[] { "UserId" },
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserClaims_AspNetUsers_UserId.MappedForeignKeys.Add(fK_AspNetUserClaims_AspNetUsers_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserClaims_AspNetUsers_UserIdFk).Add(fK_AspNetUserClaims_AspNetUsers_UserId);
            aspNetUserClaimsTable.ForeignKeyConstraints.Add(fK_AspNetUserClaims_AspNetUsers_UserId);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserClaims_AspNetUsers_UserId);
            var fK_AspNetUserLogins_AspNetUsers_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserLogins_AspNetUsers_UserId", aspNetUserLoginsTable, aspNetUsersTable,
                new[] { userIdColumn1 },
                aspNetUsersTable.FindUniqueConstraint("PK_AspNetUsers")!, ReferentialAction.Cascade);
            fK_AspNetUserLogins_AspNetUsers_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetUserLogins_AspNetUsers_UserId));
            var fK_AspNetUserLogins_AspNetUsers_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<string>",
                new[] { "UserId" },
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserLogins_AspNetUsers_UserId.MappedForeignKeys.Add(fK_AspNetUserLogins_AspNetUsers_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserLogins_AspNetUsers_UserIdFk).Add(fK_AspNetUserLogins_AspNetUsers_UserId);
            aspNetUserLoginsTable.ForeignKeyConstraints.Add(fK_AspNetUserLogins_AspNetUsers_UserId);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserLogins_AspNetUsers_UserId);
            var fK_AspNetUserRoles_AspNetRoles_RoleId = new ForeignKeyConstraint(
                "FK_AspNetUserRoles_AspNetRoles_RoleId", aspNetUserRolesTable, aspNetRolesTable,
                new[] { roleIdColumn0 },
                aspNetRolesTable.FindUniqueConstraint("PK_AspNetRoles")!, ReferentialAction.Cascade);
            fK_AspNetUserRoles_AspNetRoles_RoleId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetUserRoles_AspNetRoles_RoleId));
            var fK_AspNetUserRoles_AspNetRoles_RoleIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<string>",
                new[] { "RoleId" },
                "Microsoft.AspNetCore.Identity.IdentityRole",
                new[] { "Id" });
            fK_AspNetUserRoles_AspNetRoles_RoleId.MappedForeignKeys.Add(fK_AspNetUserRoles_AspNetRoles_RoleIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserRoles_AspNetRoles_RoleIdFk).Add(fK_AspNetUserRoles_AspNetRoles_RoleId);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fK_AspNetUserRoles_AspNetRoles_RoleId);
            aspNetRolesTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserRoles_AspNetRoles_RoleId);
            var fK_AspNetUserRoles_AspNetUsers_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserRoles_AspNetUsers_UserId", aspNetUserRolesTable, aspNetUsersTable,
                new[] { userIdColumn2 },
                aspNetUsersTable.FindUniqueConstraint("PK_AspNetUsers")!, ReferentialAction.Cascade);
            fK_AspNetUserRoles_AspNetUsers_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetUserRoles_AspNetUsers_UserId));
            var fK_AspNetUserRoles_AspNetUsers_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserRole<string>",
                new[] { "UserId" },
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserRoles_AspNetUsers_UserId.MappedForeignKeys.Add(fK_AspNetUserRoles_AspNetUsers_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserRoles_AspNetUsers_UserIdFk).Add(fK_AspNetUserRoles_AspNetUsers_UserId);
            aspNetUserRolesTable.ForeignKeyConstraints.Add(fK_AspNetUserRoles_AspNetUsers_UserId);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserRoles_AspNetUsers_UserId);
            var fK_AspNetUserTokens_AspNetUsers_UserId = new ForeignKeyConstraint(
                "FK_AspNetUserTokens_AspNetUsers_UserId", aspNetUserTokensTable, aspNetUsersTable,
                new[] { userIdColumn3 },
                aspNetUsersTable.FindUniqueConstraint("PK_AspNetUsers")!, ReferentialAction.Cascade);
            fK_AspNetUserTokens_AspNetUsers_UserId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_AspNetUserTokens_AspNetUsers_UserId));
            var fK_AspNetUserTokens_AspNetUsers_UserIdFk = RelationalModel.GetForeignKey(this,
                "Microsoft.AspNetCore.Identity.IdentityUserToken<string>",
                new[] { "UserId" },
                "BreadCharts.Core.Models.ApplicationUser",
                new[] { "Id" });
            fK_AspNetUserTokens_AspNetUsers_UserId.MappedForeignKeys.Add(fK_AspNetUserTokens_AspNetUsers_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_AspNetUserTokens_AspNetUsers_UserIdFk).Add(fK_AspNetUserTokens_AspNetUsers_UserId);
            aspNetUserTokensTable.ForeignKeyConstraints.Add(fK_AspNetUserTokens_AspNetUsers_UserId);
            aspNetUsersTable.ReferencingForeignKeyConstraints.Add(fK_AspNetUserTokens_AspNetUsers_UserId);
            var fK_SongVotes_SubmittedSongs_TrackId = new ForeignKeyConstraint(
                "FK_SongVotes_SubmittedSongs_TrackId", songVotesTable, submittedSongsTable,
                new[] { trackIdColumn },
                submittedSongsTable.FindUniqueConstraint("PK_SubmittedSongs")!, ReferentialAction.Cascade);
            fK_SongVotes_SubmittedSongs_TrackId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNullableFactory<string, string>(fK_SongVotes_SubmittedSongs_TrackId));
            var fK_SongVotes_SubmittedSongs_TrackIdFk = RelationalModel.GetForeignKey(this,
                "BreadCharts.Core.Models.SongVote",
                new[] { "TrackId" },
                "BreadCharts.Core.Models.SubmittedSong",
                new[] { "TrackId" });
            fK_SongVotes_SubmittedSongs_TrackId.MappedForeignKeys.Add(fK_SongVotes_SubmittedSongs_TrackIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_SongVotes_SubmittedSongs_TrackIdFk).Add(fK_SongVotes_SubmittedSongs_TrackId);
            songVotesTable.ForeignKeyConstraints.Add(fK_SongVotes_SubmittedSongs_TrackId);
            submittedSongsTable.ReferencingForeignKeyConstraints.Add(fK_SongVotes_SubmittedSongs_TrackId);
            return relationalModel.MakeReadOnly();
        }
    }
}
