// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityUserTokenEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserToken<string>",
                typeof(IdentityUserToken<string>),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                keyCount: 1);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            userId.SetGetter(
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.UserId(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.UserId(instance) == null);
            userId.SetSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(0) && IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.UserId(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(userId, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(userId, 0));
            userId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            userId.TypeMapping = SqliteStringTypeMapping.Default;
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userId));

            var loginProvider = runtimeEntityType.AddProperty(
                "LoginProvider",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("LoginProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<LoginProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            loginProvider.SetGetter(
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance) == null);
            loginProvider.SetSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetMaterializationSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.LoginProvider(instance) = value;
                    return instance;
                });
            loginProvider.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.LoginProvider(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(loginProvider, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(loginProvider, 1));
            loginProvider.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            loginProvider.TypeMapping = SqliteStringTypeMapping.Default;
            loginProvider.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(loginProvider));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            name.SetGetter(
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Name(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Name(instance) == null);
            name.SetSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Name(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Name(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(name, 2));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;
            name.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(name));

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(string),
                propertyInfo: typeof(IdentityUserToken<string>).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserToken<string>).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            value.SetGetter(
                string (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Value(instance),
                bool (IdentityUserToken<string> instance) => IdentityUserTokenUnsafeAccessors<string>.Value(instance) == null);
            value.SetSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.Value(instance) = value;
                    return instance;
                });
            value.SetMaterializationSetter(
                IdentityUserToken<string> (IdentityUserToken<string> instance, string value) =>
                {
                    IdentityUserTokenUnsafeAccessors<string>.Value(instance) = value;
                    return instance;
                });
            value.SetAccessors(
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Value(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => IdentityUserTokenUnsafeAccessors<string>.Value(((IdentityUserToken<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(value, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(value));
            value.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            value.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { userId, loginProvider, name });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var userId = runtimeEntityType.FindProperty("UserId");
            var loginProvider = runtimeEntityType.FindProperty("LoginProvider");
            var name = runtimeEntityType.FindProperty("Name");
            var value = runtimeEntityType.FindProperty("Value");
            var key = runtimeEntityType.FindKey(new[] { userId, loginProvider, name });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserToken<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string, string>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(value) == null ? null : ((ValueComparer<string>)(((IProperty)value).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(value))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(default(string)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string>(default(string)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserToken<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(loginProvider) == null ? null : ((ValueComparer<string>)(((IProperty)loginProvider).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(loginProvider))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(name))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserTokens");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
