// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Identity;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class IdentityRoleUnsafeAccessors<TKey>
        where TKey : IEquatable<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref TKey Id(IdentityRole<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConcurrencyStamp>k__BackingField")]
        public static extern ref string ConcurrencyStamp(IdentityRole<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(IdentityRole<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NormalizedName>k__BackingField")]
        public static extern ref string NormalizedName(IdentityRole<TKey> @this);
    }
}
