// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityUserRoleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityUserRole<string>",
                typeof(IdentityUserRole<string>),
                baseEntityType,
                propertyCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(IdentityUserRole<string>).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserRole<string>).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            userId.SetGetter(
                string (IdentityUserRole<string> instance) => IdentityUserRoleUnsafeAccessors<string>.UserId(instance),
                bool (IdentityUserRole<string> instance) => IdentityUserRoleUnsafeAccessors<string>.UserId(instance) == null);
            userId.SetSetter(
                IdentityUserRole<string> (IdentityUserRole<string> instance, string value) =>
                {
                    IdentityUserRoleUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetMaterializationSetter(
                IdentityUserRole<string> (IdentityUserRole<string> instance, string value) =>
                {
                    IdentityUserRoleUnsafeAccessors<string>.UserId(instance) = value;
                    return instance;
                });
            userId.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<string>(0) : (entry.FlaggedAsTemporary(0) && IdentityUserRoleUnsafeAccessors<string>.UserId(((IdentityUserRole<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(0) : IdentityUserRoleUnsafeAccessors<string>.UserId(((IdentityUserRole<string>)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityUserRoleUnsafeAccessors<string>.UserId(((IdentityUserRole<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(userId, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(userId, 0));
            userId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            userId.TypeMapping = SqliteStringTypeMapping.Default;
            userId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(userId));

            var roleId = runtimeEntityType.AddProperty(
                "RoleId",
                typeof(string),
                propertyInfo: typeof(IdentityUserRole<string>).GetProperty("RoleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityUserRole<string>).GetField("<RoleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            roleId.SetGetter(
                string (IdentityUserRole<string> instance) => IdentityUserRoleUnsafeAccessors<string>.RoleId(instance),
                bool (IdentityUserRole<string> instance) => IdentityUserRoleUnsafeAccessors<string>.RoleId(instance) == null);
            roleId.SetSetter(
                IdentityUserRole<string> (IdentityUserRole<string> instance, string value) =>
                {
                    IdentityUserRoleUnsafeAccessors<string>.RoleId(instance) = value;
                    return instance;
                });
            roleId.SetMaterializationSetter(
                IdentityUserRole<string> (IdentityUserRole<string> instance, string value) =>
                {
                    IdentityUserRoleUnsafeAccessors<string>.RoleId(instance) = value;
                    return instance;
                });
            roleId.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<string>(1) : (entry.FlaggedAsTemporary(1) && IdentityUserRoleUnsafeAccessors<string>.RoleId(((IdentityUserRole<string>)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(1) : IdentityUserRoleUnsafeAccessors<string>.RoleId(((IdentityUserRole<string>)(entry.Entity))))),
                string (IInternalEntry entry) => IdentityUserRoleUnsafeAccessors<string>.RoleId(((IdentityUserRole<string>)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(roleId, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(roleId, 1));
            roleId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            roleId.TypeMapping = SqliteStringTypeMapping.Default;
            roleId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(roleId));

            var key = runtimeEntityType.AddKey(
                new[] { userId, roleId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { roleId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RoleId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var userId = runtimeEntityType.FindProperty("UserId");
            var roleId = runtimeEntityType.FindProperty("RoleId");
            var key = runtimeEntityType.FindKey(new[] { userId, roleId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserRole<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(roleId) == null ? null : ((ValueComparer<string>)(((IProperty)roleId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(roleId))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<string, string>((default(string) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetValueComparer())).Snapshot(default(string))), (default(string) == null ? null : ((ValueComparer<string>)(((IProperty)roleId).GetValueComparer())).Snapshot(default(string)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<string, string>(default(string), default(string)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityUserRole<string>)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string>((source.GetCurrentValue<string>(userId) == null ? null : ((ValueComparer<string>)(((IProperty)userId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(userId))), (source.GetCurrentValue<string>(roleId) == null ? null : ((ValueComparer<string>)(((IProperty)roleId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(roleId))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetUserRoles");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
