// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Identity;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class IdentityUserTokenUnsafeAccessors<TKey>
        where TKey : IEquatable<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref TKey UserId(IdentityUserToken<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginProvider>k__BackingField")]
        public static extern ref string LoginProvider(IdentityUserToken<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(IdentityUserToken<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        public static extern ref string Value(IdentityUserToken<TKey> @this);
    }
}
