// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IdentityRoleEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Microsoft.AspNetCore.Identity.IdentityRole",
                typeof(IdentityRole),
                baseEntityType,
                propertyCount: 4,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Id(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Id(instance) == null);
            id.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Id(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Id(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(id, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = SqliteStringTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(id));

            var concurrencyStamp = runtimeEntityType.AddProperty(
                "ConcurrencyStamp",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("ConcurrencyStamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<ConcurrencyStamp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                concurrencyToken: true);
            concurrencyStamp.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) == null);
            concurrencyStamp.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(instance) = value;
                    return instance;
                });
            concurrencyStamp.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.ConcurrencyStamp(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(concurrencyStamp, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(concurrencyStamp));
            concurrencyStamp.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            concurrencyStamp.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            name.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Name(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.Name(instance) == null);
            name.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Name(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.Name(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var normalizedName = runtimeEntityType.AddProperty(
                "NormalizedName",
                typeof(string),
                propertyInfo: typeof(IdentityRole<string>).GetProperty("NormalizedName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IdentityRole<string>).GetField("<NormalizedName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            normalizedName.SetGetter(
                string (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.NormalizedName(instance),
                bool (IdentityRole instance) => IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) == null);
            normalizedName.SetSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) = value;
                    return instance;
                });
            normalizedName.SetMaterializationSetter(
                IdentityRole (IdentityRole instance, string value) =>
                {
                    IdentityRoleUnsafeAccessors<string>.NormalizedName(instance) = value;
                    return instance;
                });
            normalizedName.SetAccessors(
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.NormalizedName(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => IdentityRoleUnsafeAccessors<string>.NormalizedName(((IdentityRole)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(normalizedName, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(normalizedName));
            normalizedName.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            normalizedName.TypeMapping = SqliteStringTypeMapping.Default;
            normalizedName.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(normalizedName));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { normalizedName },
                unique: true);
            index.AddAnnotation("Relational:Name", "RoleNameIndex");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var concurrencyStamp = runtimeEntityType.FindProperty("ConcurrencyStamp");
            var name = runtimeEntityType.FindProperty("Name");
            var normalizedName = runtimeEntityType.FindProperty("NormalizedName");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityRole)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, string, string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(id))), (source.GetCurrentValue<string>(concurrencyStamp) == null ? null : ((ValueComparer<string>)(((IProperty)concurrencyStamp).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(concurrencyStamp))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(normalizedName) == null ? null : ((ValueComparer<string>)(((IProperty)normalizedName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(normalizedName))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((IdentityRole)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(id))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AspNetRoles");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
