// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Identity;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class IdentityUserLoginUnsafeAccessors<TKey>
        where TKey : IEquatable<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginProvider>k__BackingField")]
        public static extern ref string LoginProvider(IdentityUserLogin<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderKey>k__BackingField")]
        public static extern ref string ProviderKey(IdentityUserLogin<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderDisplayName>k__BackingField")]
        public static extern ref string ProviderDisplayName(IdentityUserLogin<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref TKey UserId(IdentityUserLogin<TKey> @this);
    }
}
