// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Identity;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class IdentityUserClaimUnsafeAccessors<TKey>
        where TKey : IEquatable<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(IdentityUserClaim<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ClaimType>k__BackingField")]
        public static extern ref string ClaimType(IdentityUserClaim<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ClaimValue>k__BackingField")]
        public static extern ref string ClaimValue(IdentityUserClaim<TKey> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref TKey UserId(IdentityUserClaim<TKey> @this);
    }
}
