// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using BreadCharts.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class SongVoteUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(SongVote @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TrackId>k__BackingField")]
        public static extern ref string TrackId(SongVote @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref string UserId(SongVote @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<VotedAtUtc>k__BackingField")]
        public static extern ref DateTime VotedAtUtc(SongVote @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Song>k__BackingField")]
        public static extern ref SubmittedSong Song(SongVote @this);
    }
}
