// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using BreadCharts.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    public static class SubmittedSongUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TrackId>k__BackingField")]
        public static extern ref string TrackId(SubmittedSong @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SubmittedAtUtc>k__BackingField")]
        public static extern ref DateTime SubmittedAtUtc(SubmittedSong @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SubmittedByUserId>k__BackingField")]
        public static extern ref string SubmittedByUserId(SubmittedSong @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TrackName>k__BackingField")]
        public static extern ref string TrackName(SubmittedSong @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Votes>k__BackingField")]
        public static extern ref ICollection<SongVote> Votes(SubmittedSong @this);
    }
}
