// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using BreadCharts.Core.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BreadCharts.WebApi.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SubmittedSongEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "BreadCharts.Core.Models.SubmittedSong",
                typeof(SubmittedSong),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                keyCount: 1);

            var trackId = runtimeEntityType.AddProperty(
                "TrackId",
                typeof(string),
                propertyInfo: typeof(SubmittedSong).GetProperty("TrackId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SubmittedSong).GetField("<TrackId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 100);
            trackId.SetGetter(
                string (SubmittedSong instance) => SubmittedSongUnsafeAccessors.TrackId(instance),
                bool (SubmittedSong instance) => SubmittedSongUnsafeAccessors.TrackId(instance) == null);
            trackId.SetSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.TrackId(instance) = value;
                    return instance;
                });
            trackId.SetMaterializationSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.TrackId(instance) = value;
                    return instance;
                });
            trackId.SetAccessors(
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.TrackId(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.TrackId(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(trackId, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(trackId, 0));
            trackId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            trackId.TypeMapping = SqliteStringTypeMapping.Default;
            trackId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(trackId));

            var submittedAtUtc = runtimeEntityType.AddProperty(
                "SubmittedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(SubmittedSong).GetProperty("SubmittedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SubmittedSong).GetField("<SubmittedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            submittedAtUtc.SetGetter(
                DateTime (SubmittedSong instance) => SubmittedSongUnsafeAccessors.SubmittedAtUtc(instance),
                bool (SubmittedSong instance) => SubmittedSongUnsafeAccessors.SubmittedAtUtc(instance) == default(DateTime));
            submittedAtUtc.SetSetter(
                SubmittedSong (SubmittedSong instance, DateTime value) =>
                {
                    SubmittedSongUnsafeAccessors.SubmittedAtUtc(instance) = value;
                    return instance;
                });
            submittedAtUtc.SetMaterializationSetter(
                SubmittedSong (SubmittedSong instance, DateTime value) =>
                {
                    SubmittedSongUnsafeAccessors.SubmittedAtUtc(instance) = value;
                    return instance;
                });
            submittedAtUtc.SetAccessors(
                DateTime (IInternalEntry entry) => SubmittedSongUnsafeAccessors.SubmittedAtUtc(((SubmittedSong)(entry.Entity))),
                DateTime (IInternalEntry entry) => SubmittedSongUnsafeAccessors.SubmittedAtUtc(((SubmittedSong)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(submittedAtUtc, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(submittedAtUtc));
            submittedAtUtc.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            submittedAtUtc.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var submittedByUserId = runtimeEntityType.AddProperty(
                "SubmittedByUserId",
                typeof(string),
                propertyInfo: typeof(SubmittedSong).GetProperty("SubmittedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SubmittedSong).GetField("<SubmittedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 450);
            submittedByUserId.SetGetter(
                string (SubmittedSong instance) => SubmittedSongUnsafeAccessors.SubmittedByUserId(instance),
                bool (SubmittedSong instance) => SubmittedSongUnsafeAccessors.SubmittedByUserId(instance) == null);
            submittedByUserId.SetSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.SubmittedByUserId(instance) = value;
                    return instance;
                });
            submittedByUserId.SetMaterializationSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.SubmittedByUserId(instance) = value;
                    return instance;
                });
            submittedByUserId.SetAccessors(
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.SubmittedByUserId(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.SubmittedByUserId(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(submittedByUserId, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(submittedByUserId));
            submittedByUserId.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            submittedByUserId.TypeMapping = SqliteStringTypeMapping.Default;

            var trackName = runtimeEntityType.AddProperty(
                "TrackName",
                typeof(string),
                propertyInfo: typeof(SubmittedSong).GetProperty("TrackName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SubmittedSong).GetField("<TrackName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            trackName.SetGetter(
                string (SubmittedSong instance) => SubmittedSongUnsafeAccessors.TrackName(instance),
                bool (SubmittedSong instance) => SubmittedSongUnsafeAccessors.TrackName(instance) == null);
            trackName.SetSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.TrackName(instance) = value;
                    return instance;
                });
            trackName.SetMaterializationSetter(
                SubmittedSong (SubmittedSong instance, string value) =>
                {
                    SubmittedSongUnsafeAccessors.TrackName(instance) = value;
                    return instance;
                });
            trackName.SetAccessors(
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.TrackName(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => SubmittedSongUnsafeAccessors.TrackName(((SubmittedSong)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(trackName, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(trackName));
            trackName.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            trackName.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { trackId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var trackId = runtimeEntityType.FindProperty("TrackId");
            var submittedAtUtc = runtimeEntityType.FindProperty("SubmittedAtUtc");
            var submittedByUserId = runtimeEntityType.FindProperty("SubmittedByUserId");
            var trackName = runtimeEntityType.FindProperty("TrackName");
            var key = runtimeEntityType.FindKey(new[] { trackId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            var votes = runtimeEntityType.FindNavigation("Votes");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SubmittedSong)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, DateTime, string, string>((source.GetCurrentValue<string>(trackId) == null ? null : ((ValueComparer<string>)(((IProperty)trackId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(trackId))), ((ValueComparer<DateTime>)(((IProperty)submittedAtUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(submittedAtUtc)), (source.GetCurrentValue<string>(submittedByUserId) == null ? null : ((ValueComparer<string>)(((IProperty)submittedByUserId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(submittedByUserId))), (source.GetCurrentValue<string>(trackName) == null ? null : ((ValueComparer<string>)(((IProperty)trackName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(trackName))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SubmittedSong)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, object>((source.GetCurrentValue<string>(trackId) == null ? null : ((ValueComparer<string>)(((IProperty)trackId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(trackId))), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<ICollection<SongVote>>(votes)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SubmittedSongs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
